version: '3.5'

services:
  library_postgres:
    container_name: library_postgres
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5433"
    command: -p 5433
    networks:
      - postgres
    restart: on-failure

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

networks:
  postgres:
    driver: bridge

volumes:
  postgres: