version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5433"
    command: -p 5433
    networks:
      - postgres
    restart: on-failure

networks:
  postgres:
    driver: bridge

volumes:
  postgres: