spring:
  main:
    banner-mode: off
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: public
  mail:
    from: info@library.ru
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cron:
  book-use-time-expire:
    expression: "0 8 * * * *"

library:
  book-use-number-days: 14


